### ISSUE TITLE
Nested folders Tracking Task

### ISSUE THREAD

**Issue by srivastavankit** [uber/idl#67]
- [ ] Ensure that we dont allow any nested folder to override an existing service method. Especially the case where we have a github.com/org.git repo and github.com/org/s.git. In this case any nested folder of github.com/org should not override github.com/org/s

- [ ] `idl fetch` should not allow nested folder fetch.

**Comment by kriskowal** [comment]
I would clarify the first:

- [ ] ensure that no publish introduces a package that is a prefix of any existing package.
- [ ] ensure that no publish introduces a package that has any existing package as a prefix.

I think we can protect both cases on `publish`. I don't think we can avoid trampling the working copy in `fetch`.
